ginames = {
    'albedo': ['Albedo', 'Альбедо'],
    'aloy': ['Aloy', 'Элой'],
    'amber': ['Amber', 'Эмбер'],
    'ayaka': ['Ayaka', 'Аяка'],
    'ayato': ['Ayato', 'Аято'],
    'barbara': ['Barbara', 'Барбара'],
    'beidou': ['Beidou', 'Бэй Доу', 'Бэйдоу', 'Бей Доу', 'Бейдоу', 'Бэй До', 'Бэйдо', 'Бей До', 'Бейдо'],
    'bennett': ['Bennett', 'Беннет', 'Беннетт', 'Бенет', 'Бенетт'],
    'candace': ['Candace', 'Кандакия'],
    'chongyun': ['Chongyun', 'Чун Юнь', 'Чунь Юнь', 'Чун Юн', 'Чунь Юн'],
    'collei': ['Collei', 'Коллеи'],
    'cyno': ['Cyno', 'Сайно'],
    'diluc': ['Diluc', 'Дилюк'],
    'diona': ['Diona', 'Диона'],
    'dori': ['Dori', 'Дори'],
    'eula': ['Eula', 'Эола'],
    'fischl': ['Fischl', 'Фишль'],
    'ganyu': ['Ganyu', 'Гань Юй', 'Гань'],
    'gorou': ['Gorou', 'Горо'],
    'heizou': ['Heizou', 'Хэйдзо', 'Хейдзо'],
    'hutao': ['Hu Tao', 'Ху Тао'],
    'itto': ['Itto', 'Итто'],
    'jean': ['Jean', 'Джинн', 'Джин'],
    'kaeya': ['Kaeya', 'Кэйа', 'Кэйя'],
    'kazuha': ['Kazuha', 'Кадзуха', 'Казуха'],
    'keqing': ['Keqing', 'Кэ Цин', 'Кэцин'],
    'klee': ['Klee', 'Кли'],
    'kokomi': ['Kokomi', 'Кокоми'],
    'kuki': ['Kuki', 'Куки'],
    'layla': ['Layla', 'Лайла'],
    'lisa': ['Lisa', 'Лиза'],
    'mona': ['Mona', 'Мона'],
    'nahida': ['Nahida', 'Нахида'],
    'nilou': ['Nilou', 'Нилу'],
    'ningguang': ['Ningguang', 'Ning', 'Нин Гуан', 'Нина'],
    'noelle': ['Noelle', 'Ноэлль', 'Ноэль'],
    'qiqi': ['Qiqi', 'Ци ци'],
    'raiden': ['Raiden', 'Райден', 'Баал'],
    'razor': ['Razor', 'Рэйзор', 'Разор'],
    'rosaria': ['Rosaria', 'Розария'],
    'sara': ['Sara', 'Сара'],
    'sayu': ['Sayu', 'Саю'],
    'shenhe': ['Shenhe', 'Шэнь Хэ'],
    'sucrose': ['Sucrose', 'Сахароза'],
    'tartaglia': ['Tartaglia', 'Childe', 'Тарталья', 'Чайлд', 'Торт'],
    'thoma': ['Thoma', 'Тома'],
    'tighnari': ['Tighnari', 'Тигнари'],
    'venti': ['Venti', 'Венти'],
    'xiangling': ['Xiangling', 'Сян Лин'],
    'xiao': ['Xiao', 'Сяо'],
    'xingqiu': ['Xingqiu', 'Син Цю'],
    'xinyan': ['Xinyan', 'Синь Янь'],
    'yaemiko': ['Yae Miko', 'Yae', 'Яэ Мико', 'Яэ', 'Мико'],
    'yanfei': ['Yanfei', 'Янь Фэй', 'Яна'],
    'yelan': ['Yelan', 'Е Лань'],
    'yoimiya': ['Yoimiya', 'Yoi', 'Ёимия', 'Йоимия'],
    'yunjin': ['Yun Jin', 'Юнь Цзинь', 'Юнь'],
    'zhongli': ['Zhongli', 'Чжун Ли', 'Чжун']
}